name: Terraform

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  tf:
    runs-on: ubuntu-latest
    steps:
      - name: ls
        run: |
          pwd
          ls

      - name: customer repo checkout
        uses: actions/checkout@v4
        with:
          path: tf-gcp-customer

      - name: ls
        run: |
          pwd
          ls
          
      - name: base repo checkout
        uses: actions/checkout@v4
        with:
          repository: 'SunnyOswal/tf-gcp-base'
          path: tf-gcp-base
          ref: 'main'
          token: '${{ secrets.GH_TOKEN }}'
      

      - name: ls
        run: |
          pwd
          ls
      
      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Copy Customer repo files to base repo dir
        run: |
          pwd
          ls
          cp -r ../tf-gcp-customer . 
          ls

      - name: Terraform Apply
        run: |
          terraform init
          terraform plan
          # terraform apply
