name: Terraform

# Controls when the workflow will run
on:
  # Triggers the workflow on push events for all branches except the "main" branch
  push:
    branches:
      - '*'
      - '!main'
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  tf:
    runs-on: ubuntu-latest
    # Environment will be branch name of the customer.
    # Each customer will have it's own env which will have it's respective secrets.
    environment: ${{ github.ref_name }}
    steps:
      - name: customer repo checkout
        uses: actions/checkout@v4
        with:
          path: tf-gcp-customer
          
      - name: base repo checkout
        uses: actions/checkout@v4
        with:
          repository: 'SunnyOswal/tf-gcp-base'
          path: tf-gcp-base
          ref: 'main'
          token: '${{ secrets.GH_TOKEN }}'

      - name: Copy Customer repo files to base repo dir
        run: cp -r ./tf-gcp-customer/* ./tf-gcp-base

      - name: GCP Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
          
      - name: Terraform Apply
        run: |
          cd tf-gcp-base
          terraform init
          terraform plan -var-file="customer.tfvars" -out=customer.tfplan
          terraform apply -auto-approve customer.tfplan
          terraform destroy -auto-approve
