name: Terraform

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  tf:
    runs-on: ubuntu-latest
    steps:      
      # base repo checkout
      - uses: actions/checkout@v4
        with:
          repository: 'SunnyOswal/tf-gcp-base'
          # The branch, tag or SHA to checkout. When checking out the repository that
          # triggered a workflow, this defaults to the reference or SHA for that event.
          # Otherwise, uses the default branch.
          ref: 'main'
          token: '${{ secrets.GH_TOKEN }}'

      # current repo checkout
      - uses: actions/checkout@v4
      
      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      # Runs a single command using the runners shell
      - name: Copy Customer repo files to base repo dir
        run: |
          pwd
          ls
          cp -r . ./tf-gcp-base
          ls

      - name: Terraform Apply
        run: |
          terraform init
          terraform plan
          # terraform apply
